### ISSUE TITLE
Turn Single

### ISSUE THREAD

**Issue by cranhandler** [dcmorse/contra#193] opened 2017-06-10 03:46 UTC
Will be needed for English Support, also ie Galopede 

aka turn alone

http://contradb.com/dances/61

**Comment by dcmorse** [comment] 2017-06-10 11:40
I think this is a duplicate of https://github.com/dcmorse/contra/issues/145

**Comment by dcmorse** [comment] 2017-10-23 03:03
closing duplicate

**Closed by dcmorse** 2017-10-23 03:03 UTC
Labels: duplicate, figure
